[theme]
mode = "dark"
source = "custom"
custom_palette = "Tron-Ares"

[shell]
corner_radius_scale = 0

[bar.main]
capsule = true

[dock]
enabled             = true
position            = "bottom"
icon_size           = 48
main_axis_padding   = 16
cross_axis_padding  = 8
item_spacing        = 6
background_opacity  = 0.88
radius              = 16
margin_h            = 0
margin_v            = 8
shadow              = true
show_running        = true
auto_hide           = false
reserve_space       = true
active_scale        = 1.0
inactive_scale      = 0.85
magnification       = true
magnification_scale = 1.45
active_opacity      = 1.0
inactive_opacity    = 0.85
show_dots           = false
show_instance_count = true
launcher_position   = "start"
launcher_icon       = "grid-dots"
active_monitor_only = false
pinned              = ["kitty", "google-chrome", "zeditor", "code"]
