keys:
  - &admin age16yh6y5f06rzuk0d43y2lknvcsgn9rpe597j5wuhqzfmlgw23l48qrnujj7  # Your personal age recipient
  - &system age1nf8a0ned5390gst6n4l57z6g5gp69e0dtyayehl4dghsqqkw8gusxzruuj # Your system's SSH host key

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *system
