# Tron: Ares (Dillinger Grid)

foreground            #ff0000
background            #080000
selection_foreground  #ffffff
selection_background  #5a1010

cursor                #ffffff
cursor_text_color     #080000

active_border_color   #ff0000
inactive_border_color #4f0000

active_tab_foreground   #080000
active_tab_background   #ff0000
inactive_tab_foreground #ff0000
inactive_tab_background #1a0000
tab_bar_background      #080000

# Normal colors
color0  #1a0000
color1  #ff6600
color2  #0dbc79
color3  #cd9000
color4  #d4d4d4
color5  #bc3fbc
color6  #11a8cd
color7  #e5e5e5

# Bright colors
color8  #4f0000
color9  #ff8c00
color10 #23d18b
color11 #e5c07b
color12 #ffffff
color13 #d670d6
color14 #29b8db
color15 #ffffff
