color0 #371b1d
color1 #ad1e2b
color2 #e56772
color3 #e18c51
color4 #e1d451
color5 #ec929a
color6 #ecb792
color7 #f3f2f2
color8 #756162
color9 #ad1e2b
color10 #e56772
color11 #e18c51
color12 #e1d451
color13 #ec929a
color14 #ecb792
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291416
background            #291416
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371b1d
active_border_color   #e56772
inactive_border_color #371b1d
url_color             #e56772

active_tab_foreground   #25181a
active_tab_background   #e56772
inactive_tab_foreground #b6afaf
inactive_tab_background #371b1d
cursor_trail_color      #b6afaf
